### ISSUE TITLE
SEPparser.py SyntaxWarning & ModuleNotFound Error

### ISSUE THREAD

**Issue by asinclair21** [Beercow/SEPparser#5]
I just downloaded the master folder containing everything for SEPparser & when I went to test out the script for SEPparser.py, I received the following error message:

rey@ubuntu:~/Desktop/SEPparser-master$ python3 SEPparser.py -h
SEPparser.py:2880: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  while check is not b'0':
SEPparser.py:2888: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if check is b'0':
Traceback (most recent call last):
  File "SEPparser.py", line 11, in <module>
    from dissect import cstruct
ModuleNotFoundError: No module named 'dissect'

**Comment by Beercow** [comment]
The SyntaxWarning can be ignored. It is fixed in the  Dev branch and I would use that for now. As for the module, you would be missing dissect. It can be installed with 
``` pip install dissect.cstruct ```
